apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2021-12-26T12:29:23Z"
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "319"
  uid: 1665ccf6-8139-4c50-8442-107286996cf8
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-proxy
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:bootstrappers:kubeadm:default-node-token
