apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2021-12-26T12:29:19Z"
  name: kubeadm:kubelet-config-1.22
  namespace: kube-system
  resourceVersion: "240"
  uid: cabfdfdc-6f3e-4ebd-a035-5869e3dd5208
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeadm:kubelet-config-1.22
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:bootstrappers:kubeadm:default-node-token
