apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2021-12-26T12:29:17Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system::extension-apiserver-authentication-reader
  namespace: kube-system
  resourceVersion: "222"
  uid: 90a034bb-f098-4dd4-aab7-dc3ed7417dce
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-controller-manager
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-scheduler
