apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-01-29T19:55:48Z"
  name: endpointslicemirroring-controller
  namespace: kube-system
  resourceVersion: "356"
  uid: 9934246d-ce22-4585-b2a1-68b6519881cd
secrets:
- name: endpointslicemirroring-controller-token-9vfvh
