apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-01-29T19:55:34Z"
  name: pvc-protection-controller
  namespace: kube-system
  resourceVersion: "257"
  uid: 695f5f44-9e2b-428f-9706-1f28316e076c
secrets:
- name: pvc-protection-controller-token-8gft2
