apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2022-01-29T19:55:34Z"
  name: ttl-controller
  namespace: kube-system
  resourceVersion: "251"
  uid: 379732d6-bcb6-41ce-a018-0b2426574114
secrets:
- name: ttl-controller-token-gsxjs
