apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-01-29T19:55:28Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:pv-protection-controller
  resourceVersion: "146"
  uid: 207f7dee-4083-4db6-aa7d-22c0e70c2746
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
