apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-01-29T19:55:22Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:monitoring
  resourceVersion: "68"
  uid: fe1c35f2-b1aa-4021-a436-c47ba0d17aca
rules:
- nonResourceURLs:
  - /healthz
  - /healthz/*
  - /livez
  - /livez/*
  - /metrics
  - /readyz
  - /readyz/*
  verbs:
  - get
