apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-01-29T19:55:27Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:pod-garbage-collector
  resourceVersion: "135"
  uid: 154d0e50-b84d-40c0-a018-930969bc8ede
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
