apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2021-12-26T12:29:22Z"
  name: system:coredns
  resourceVersion: "292"
  uid: 6966bd4c-3500-4f8d-9cfb-c7c357675408
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:coredns
subjects:
- kind: ServiceAccount
  name: coredns
  namespace: kube-system
