apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2021-12-26T12:29:16Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:service-controller
  resourceVersion: "203"
  uid: 153cf4ce-2667-4b83-85ae-85373691d1be
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:service-controller
subjects:
- kind: ServiceAccount
  name: service-controller
  namespace: kube-system
