apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2021-12-26T12:29:14Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:endpoint-controller
  resourceVersion: "178"
  uid: bf9c3b1e-23c1-4b42-aaf3-090a118f94e7
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:endpoint-controller
subjects:
- kind: ServiceAccount
  name: endpoint-controller
  namespace: kube-system
