apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2021-12-26T12:29:12Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:resourcequota-controller
  resourceVersion: "137"
  uid: d583b799-e422-4ced-abdd-f401f866d3d0
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - resourcequotas/status
  verbs:
  - update
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
