apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2022-01-29T19:55:34Z"
  name: kubeadm:nodes-kubeadm-config
  namespace: kube-system
  resourceVersion: "239"
  uid: b8200845-5b51-4b86-a2c5-5694cf55fc1d
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubeadm-config
  resources:
  - configmaps
  verbs:
  - get
