apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2022-01-29T19:55:21Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1.authentication.k8s.io
  resourceVersion: "5"
  uid: 9ed9dae0-b096-417b-a10b-6093e0425663
spec:
  group: authentication.k8s.io
  groupPriorityMinimum: 17700
  version: v1
  versionPriority: 15
status:
  conditions:
  - lastTransitionTime: "2022-01-29T19:55:21Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
