apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2022-01-29T19:55:21Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v2beta1.autoscaling
  resourceVersion: "16"
  uid: 8879346d-75ed-475c-8281-49e2542d5f2a
spec:
  group: autoscaling
  groupPriorityMinimum: 17500
  version: v2beta1
  versionPriority: 9
status:
  conditions:
  - lastTransitionTime: "2022-01-29T19:55:21Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
