apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-12-26T12:29:33Z"
  name: clusterrole-aggregation-controller
  namespace: kube-system
  resourceVersion: "358"
  uid: 6a975b97-e8a3-49a8-b1cd-dbdb7a20b5c6
secrets:
- name: clusterrole-aggregation-controller-token-jj4rn
