apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-12-26T12:29:22Z"
  name: cronjob-controller
  namespace: kube-system
  resourceVersion: "313"
  uid: 81d820f5-8374-4e7c-bf6c-c912e40c5fb5
secrets:
- name: cronjob-controller-token-gnx6p
