apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-12-26T12:29:20Z"
  name: pod-garbage-collector
  namespace: kube-system
  resourceVersion: "258"
  uid: ea78f8f0-11da-46ed-bbff-ebabcca6bfe2
secrets:
- name: pod-garbage-collector-token-hbvmx
