apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-12-26T12:29:36Z"
  name: service-account-controller
  namespace: kube-system
  resourceVersion: "388"
  uid: f87a85a1-73cf-4c11-a5c0-9ce8fdd8813e
secrets:
- name: service-account-controller-token-zjtrv
