apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2021-12-26T12:29:37Z"
  name: token-cleaner
  namespace: kube-system
  resourceVersion: "415"
  uid: d8c0f1b9-c3ee-455a-8f40-1ee053cea24e
secrets:
- name: token-cleaner-token-hgkqt
