apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2021-12-26T12:29:06Z"
  generation: 1
  name: node-high
  resourceVersion: "60"
  uid: 99a74bcb-23b6-488c-add2-17dc1262c218
spec:
  limited:
    assuredConcurrencyShares: 40
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 50
        queues: 64
      type: Queue
  type: Limited
status: {}
