apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2021-12-26T12:29:06Z"
  generation: 1
  name: system
  resourceVersion: "57"
  uid: 338581d0-6155-4243-b397-59fbdc21ffc4
spec:
  limited:
    assuredConcurrencyShares: 30
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 50
        queues: 64
      type: Queue
  type: Limited
status: {}
