apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: PriorityLevelConfiguration
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2021-12-26T12:29:06Z"
  generation: 1
  name: workload-high
  resourceVersion: "66"
  uid: 44136160-e317-41b9-bfe2-fcee1f434bd7
spec:
  limited:
    assuredConcurrencyShares: 40
    limitResponse:
      queuing:
        handSize: 6
        queueLengthLimit: 50
        queues: 128
      type: Queue
  type: Limited
status: {}
