apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2022-01-04T17:03:28Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  name: v1beta1.appprotect.f5.com
  resourceVersion: "1071112"
  uid: 10cec4b2-e0e6-4da6-a510-d2b951a59b93
spec:
  group: appprotect.f5.com
  groupPriorityMinimum: 1000
  version: v1beta1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2022-01-04T17:03:28Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
