apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2021-12-26T12:29:18Z"
  name: kubeadm:nodes-kubeadm-config
  namespace: kube-system
  resourceVersion: "234"
  uid: 441d30d6-9942-4611-a384-a4121b7e1105
rules:
- apiGroups:
  - ""
  resourceNames:
  - kubeadm-config
  resources:
  - configmaps
  verbs:
  - get
