apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2021-12-26T12:29:17Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:token-cleaner
  namespace: kube-system
  resourceVersion: "218"
  uid: ee6cb443-f9dc-4ee5-8e57-7fb48863710f
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
