apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-01-29T19:55:31Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:generic-garbage-collector
  resourceVersion: "193"
  uid: 5177390d-c30d-4fbb-9aee-f539d7a0649c
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:generic-garbage-collector
subjects:
- kind: ServiceAccount
  name: generic-garbage-collector
  namespace: kube-system
