apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-01-29T19:55:30Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:endpointslice-controller
  resourceVersion: "184"
  uid: 23a6fd50-611a-4602-920d-4909f9727daa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:endpointslice-controller
subjects:
- kind: ServiceAccount
  name: endpointslice-controller
  namespace: kube-system
