apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-01-29T19:55:29Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:volume-scheduler
  resourceVersion: "164"
  uid: c7a40ac5-56a3-42f5-aea1-3787c26d28d2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:volume-scheduler
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-scheduler
