apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-01-29T19:55:30Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:expand-controller
  resourceVersion: "189"
  uid: 51fef59b-2ea3-4d45-8f15-019f27b0e770
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:expand-controller
subjects:
- kind: ServiceAccount
  name: expand-controller
  namespace: kube-system
