apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-01-29T19:55:32Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:service-controller
  resourceVersion: "207"
  uid: 9b8c5cc6-607f-4799-80cf-31525ecbd67b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:service-controller
subjects:
- kind: ServiceAccount
  name: service-controller
  namespace: kube-system
