apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2022-01-29T19:55:32Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:resourcequota-controller
  resourceVersion: "204"
  uid: d7bb3784-0367-41b0-9173-98142f97294f
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:resourcequota-controller
subjects:
- kind: ServiceAccount
  name: resourcequota-controller
  namespace: kube-system
