apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2021-12-26T12:29:12Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:root-ca-cert-publisher
  resourceVersion: "147"
  uid: 73778e4d-278f-4c61-88ce-010488de9990
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - update
- apiGroups:
  - ""
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - patch
  - update
