apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-12-26T12:29:38Z"
  generateName: coredns-78fcd69978-
  labels:
    k8s-app: kube-dns
    pod-template-hash: 78fcd69978
  name: coredns-78fcd69978-67r9q
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: coredns-78fcd69978
    uid: e3d31c61-f958-422c-aff6-07457f4b08ff
  resourceVersion: "1055283"
  uid: ca8308fc-5875-41da-bde4-cb9baafa2f3d
spec:
  containers:
  - args:
    - -conf
    - /etc/coredns/Corefile
    image: k8s.gcr.io/coredns/coredns:v1.8.4
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 5
      httpGet:
        path: /health
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 60
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 5
    name: coredns
    ports:
    - containerPort: 53
      name: dns
      protocol: UDP
    - containerPort: 53
      name: dns-tcp
      protocol: TCP
    - containerPort: 9153
      name: metrics
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /ready
        port: 8181
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 170Mi
      requests:
        cpu: 100m
        memory: 70Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - all
      readOnlyRootFilesystem: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/coredns
      name: config-volume
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-9cmph
      readOnly: true
  dnsPolicy: Default
  enableServiceLinks: true
  nodeName: k8s001
  nodeSelector:
    kubernetes.io/os: linux
  preemptionPolicy: PreemptLowerPriority
  priority: 2000000000
  priorityClassName: system-cluster-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: coredns
  serviceAccountName: coredns
  terminationGracePeriodSeconds: 30
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - configMap:
      defaultMode: 420
      items:
      - key: Corefile
        path: Corefile
      name: coredns
    name: config-volume
  - name: kube-api-access-9cmph
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-12-26T12:31:12Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-01-04T13:39:40Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-01-04T13:39:40Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-12-26T12:31:11Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://5b382c7cb22dda0a0faf7065a0f146f376020c677dcdb592c5b0be2c47b9f9a8
    image: k8s.gcr.io/coredns/coredns:v1.8.4
    imageID: docker-pullable://k8s.gcr.io/coredns/coredns@sha256:6e5a02c21641597998b4be7cb5eb1e7b02c0d8d23cce4dd09f4682d463798890
    lastState:
      terminated:
        containerID: docker://64aeccec33bf2d0ac4b2d8621705d84709d0459f9235e47c18babe941d63cb71
        exitCode: 255
        finishedAt: "2022-01-04T13:38:36Z"
        reason: Error
        startedAt: "2021-12-30T07:53:31Z"
    name: coredns
    ready: true
    restartCount: 3
    started: true
    state:
      running:
        startedAt: "2022-01-04T13:39:37Z"
  hostIP: 192.168.88.81
  phase: Running
  podIP: 10.244.1.53
  podIPs:
  - ip: 10.244.1.53
  qosClass: Burstable
  startTime: "2021-12-26T12:31:12Z"
