apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-12-26T12:30:32Z"
  generateName: kube-flannel-ds-
  labels:
    app: flannel
    controller-revision-hash: cdfcf6866
    pod-template-generation: "1"
    tier: node
  name: kube-flannel-ds-2xxhk
  namespace: kube-system
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: DaemonSet
    name: kube-flannel-ds
    uid: 4a2c4ffb-3eb6-42f6-ac67-d7cd2d65c146
  resourceVersion: "1071316"
  uid: 87f7a080-90db-4852-ba15-23102308fce8
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchFields:
          - key: metadata.name
            operator: In
            values:
            - k8s000
  containers:
  - args:
    - --ip-masq
    - --kube-subnet-mgr
    command:
    - /opt/bin/flanneld
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.namespace
    image: quay.io/coreos/flannel:v0.15.1
    imagePullPolicy: IfNotPresent
    name: kube-flannel
    resources:
      limits:
        cpu: 100m
        memory: 50Mi
      requests:
        cpu: 100m
        memory: 50Mi
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
      privileged: false
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /run/flannel
      name: run
    - mountPath: /etc/kube-flannel/
      name: flannel-cfg
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5r2gv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  initContainers:
  - args:
    - -f
    - /flannel
    - /opt/cni/bin/flannel
    command:
    - cp
    image: rancher/mirrored-flannelcni-flannel-cni-plugin:v1.0.0
    imagePullPolicy: IfNotPresent
    name: install-cni-plugin
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/cni/bin
      name: cni-plugin
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5r2gv
      readOnly: true
  - args:
    - -f
    - /etc/kube-flannel/cni-conf.json
    - /etc/cni/net.d/10-flannel.conflist
    command:
    - cp
    image: quay.io/coreos/flannel:v0.15.1
    imagePullPolicy: IfNotPresent
    name: install-cni
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/cni/net.d
      name: cni
    - mountPath: /etc/kube-flannel/
      name: flannel-cfg
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-5r2gv
      readOnly: true
  nodeName: k8s000
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: flannel
  serviceAccountName: flannel
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/disk-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/memory-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/pid-pressure
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/unschedulable
    operator: Exists
  - effect: NoSchedule
    key: node.kubernetes.io/network-unavailable
    operator: Exists
  volumes:
  - hostPath:
      path: /run/flannel
      type: ""
    name: run
  - hostPath:
      path: /opt/cni/bin
      type: ""
    name: cni-plugin
  - hostPath:
      path: /etc/cni/net.d
      type: ""
    name: cni
  - configMap:
      defaultMode: 420
      name: kube-flannel-cfg
    name: flannel-cfg
  - name: kube-api-access-5r2gv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-04T13:39:45Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-01-04T17:04:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-01-04T17:04:17Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-12-26T12:30:32Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a8978ab90510a2be321f3c681a14ac666d460c4e14b599b8ed2c0c4ec982b15d
    image: quay.io/coreos/flannel:v0.15.1
    imageID: docker-pullable://quay.io/coreos/flannel@sha256:9a296fbb67790659adc3701e287adde3c59803b7fcefe354f1fc482840cdb3d9
    lastState:
      terminated:
        containerID: docker://949b792779142753a7e15af44b65c3661330a02f226da3ceb52f647d8ee8bc65
        exitCode: 255
        finishedAt: "2022-01-04T17:02:34Z"
        reason: Error
        startedAt: "2022-01-04T13:39:53Z"
    name: kube-flannel
    ready: true
    restartCount: 11
    started: true
    state:
      running:
        startedAt: "2022-01-04T17:04:16Z"
  hostIP: 192.168.88.80
  initContainerStatuses:
  - containerID: docker://b85f6a4337a1c9d17dfb410d4bfd7aafc4fd12bf47fa90e2af010e3152bbef01
    image: rancher/mirrored-flannelcni-flannel-cni-plugin:v1.0.0
    imageID: docker-pullable://rancher/mirrored-flannelcni-flannel-cni-plugin@sha256:bfe8f30c74bc6f31eba0cc6659e396dbdd5ab171314ed542cc238ae046660ede
    lastState: {}
    name: install-cni-plugin
    ready: true
    restartCount: 1
    state:
      terminated:
        containerID: docker://b85f6a4337a1c9d17dfb410d4bfd7aafc4fd12bf47fa90e2af010e3152bbef01
        exitCode: 0
        finishedAt: "2022-01-04T17:04:04Z"
        reason: Completed
        startedAt: "2022-01-04T17:04:04Z"
  - containerID: docker://04b057cd9477824c1192468f0b7f620b957a4ea68d73cac2b251e6ea79cff71b
    image: quay.io/coreos/flannel:v0.15.1
    imageID: docker-pullable://quay.io/coreos/flannel@sha256:9a296fbb67790659adc3701e287adde3c59803b7fcefe354f1fc482840cdb3d9
    lastState: {}
    name: install-cni
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://04b057cd9477824c1192468f0b7f620b957a4ea68d73cac2b251e6ea79cff71b
        exitCode: 0
        finishedAt: "2022-01-04T17:04:10Z"
        reason: Completed
        startedAt: "2022-01-04T17:04:10Z"
  phase: Running
  podIP: 192.168.88.80
  podIPs:
  - ip: 192.168.88.80
  qosClass: Burstable
  startTime: "2021-12-26T12:30:32Z"
