apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: 27b1812f963af626f1409dbea4da7d4b
    kubernetes.io/config.mirror: 27b1812f963af626f1409dbea4da7d4b
    kubernetes.io/config.seen: "2021-12-26T15:28:55.411264316+03:00"
    kubernetes.io/config.source: file
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2021-12-26T12:29:13Z"
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler-k8s000
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: k8s000
    uid: 6588a2f6-cead-4dba-af3d-548cfc85b695
  resourceVersion: "1699543"
  uid: ee0459be-e7ea-48d8-a897-5d701bbfe80a
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    - --port=0
    image: k8s.gcr.io/kube-scheduler:v1.22.5
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: k8s000
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-04T17:03:23Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-01-08T07:12:17Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-01-08T07:12:17Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-01-04T17:03:23Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://6711d2a38cc886e9639f6abeabfafa592e1e0905fe597c30b9642a7dbcaecaa6
    image: k8s.gcr.io/kube-scheduler:v1.22.5
    imageID: docker-pullable://k8s.gcr.io/kube-scheduler@sha256:96df4d3ff6be2e23395234619e306dec6879acc85748082b3780173ae8d8b5f4
    lastState:
      terminated:
        containerID: docker://e988b7979f126bc4750333a85730d9c0941a7a79dc9875f27bd06ae363ddfeb5
        exitCode: 1
        finishedAt: "2022-01-08T07:11:52Z"
        reason: Error
        startedAt: "2022-01-08T06:59:14Z"
    name: kube-scheduler
    ready: true
    restartCount: 20
    started: true
    state:
      running:
        startedAt: "2022-01-08T07:12:03Z"
  hostIP: 192.168.88.80
  phase: Running
  podIP: 192.168.88.80
  podIPs:
  - ip: 192.168.88.80
  qosClass: Burstable
  startTime: "2022-01-04T17:03:23Z"
