apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2022-01-04T17:03:28Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: "true"
  name: v1.k8s.nginx.org
  resourceVersion: "1071114"
  uid: 620d9b73-528d-4cda-bf7a-5faa2c61a6ec
spec:
  group: k8s.nginx.org
  groupPriorityMinimum: 1000
  version: v1
  versionPriority: 100
status:
  conditions:
  - lastTransitionTime: "2022-01-04T17:03:28Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
