apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2021-12-26T12:29:05Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1beta1.storage.k8s.io
  resourceVersion: "37"
  uid: eed80792-1440-4c84-a532-fe6962252ef6
spec:
  group: storage.k8s.io
  groupPriorityMinimum: 16800
  version: v1beta1
  versionPriority: 9
status:
  conditions:
  - lastTransitionTime: "2021-12-26T12:29:05Z"
    message: Local APIServices are always available
    reason: Local
    status: "True"
    type: Available
