apiVersion: flowcontrol.apiserver.k8s.io/v1beta1
kind: FlowSchema
metadata:
  annotations:
    apf.kubernetes.io/autoupdate-spec: "true"
  creationTimestamp: "2021-12-26T12:29:04Z"
  generation: 1
  name: system-nodes
  resourceVersion: "58"
  uid: 5ed1cde7-a6cd-4c7c-ae6e-fc3facd6b7a4
spec:
  distinguisherMethod:
    type: ByUser
  matchingPrecedence: 500
  priorityLevelConfiguration:
    name: system
  rules:
  - nonResourceRules:
    - nonResourceURLs:
      - '*'
      verbs:
      - '*'
    resourceRules:
    - apiGroups:
      - '*'
      clusterScope: true
      namespaces:
      - '*'
      resources:
      - '*'
      verbs:
      - '*'
    subjects:
    - group:
        name: system:nodes
      kind: Group
status:
  conditions:
  - lastTransitionTime: "2021-12-26T12:29:06Z"
    message: This FlowSchema references the PriorityLevelConfiguration object named
      "system" and it exists
    reason: Found
    status: "False"
    type: Dangling
