apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/config.hash: a5aa994a30cb78db3d28f705e4f8c677
    kubernetes.io/config.mirror: a5aa994a30cb78db3d28f705e4f8c677
    kubernetes.io/config.seen: "2022-01-29T22:55:07.446995860+03:00"
    kubernetes.io/config.source: file
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  creationTimestamp: "2022-01-29T19:55:29Z"
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler-k8s000
  namespace: kube-system
  ownerReferences:
  - apiVersion: v1
    controller: true
    kind: Node
    name: k8s000
    uid: 980e51dd-f99f-4c1c-a9b0-a5fb00bf9a9b
  resourceVersion: "1652"
  uid: 412cb21e-26b7-43a8-81f6-6312027f5878
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=true
    image: k8s.gcr.io/kube-scheduler:v1.23.3
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 15
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  nodeName: k8s000
  preemptionPolicy: PreemptLowerPriority
  priority: 2000001000
  priorityClassName: system-node-critical
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    operator: Exists
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-29T19:55:37Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-01-29T20:10:08Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-01-29T20:10:08Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-01-29T19:55:37Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://e72d950e79f9ffea4bb4dcebd8a34b6ba5750af69cec3daf8dd2ca029e94ad79
    image: k8s.gcr.io/kube-scheduler:v1.23.3
    imageID: docker-pullable://k8s.gcr.io/kube-scheduler@sha256:32308abe86f7415611ca86ee79dd0a73e74ebecb2f9e3eb85fc3a8e62f03d0e7
    lastState:
      terminated:
        containerID: docker://21ec53ecb3aa0f8dcd97e52d4eee13990ac61f590eddb1d4cc020903c34df798
        exitCode: 0
        finishedAt: "2022-01-29T20:07:18Z"
        reason: Completed
        startedAt: "2022-01-29T19:55:18Z"
    name: kube-scheduler
    ready: true
    restartCount: 1
    started: true
    state:
      running:
        startedAt: "2022-01-29T20:09:54Z"
  hostIP: 192.168.88.80
  phase: Running
  podIP: 192.168.88.80
  podIPs:
  - ip: 192.168.88.80
  qosClass: Burstable
  startTime: "2022-01-29T19:55:37Z"
